{{ if .Values.staging.enable }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: {{ .Values.staging.server }}
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: {{ .Values.email }}
            apiTokenSecretRef:
              name: {{ .Values.staging.tokensecret }}
              key: cloudflare-token
        selector:
          dnsZones:
            {{- range .Values.dnsZones }}
            - {{ . | quote }}
            {{- end }}
{{ end }}