{{ if .Values.letsencrypt.production.enable }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: {{ .Values.letsencrypt.production.server }}
    email: {{ .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: {{ .Values.letsencrypt.email }}
            apiTokenSecretRef:
              name: {{ .Values.letsencrypt.production.tokensecret }}
              key: cloudflare-token
        selector:
          dnsZones:
            {{- range .Values.letsencrypt.dnsZones }}
            - {{ . | quote }}
            {{- end }}
{{ end }}