apiVersion: v1
kind: Service
metadata:
  name: pipelines-as-code-webhook
  
  labels:
    app.kubernetes.io/version: "v0.27.1"
    app.kubernetes.io/part-of: pipelines-as-code
spec:
  ports:
    - name: https-webhook
      port: 443
      targetPort: 8443
  selector:
    app.kubernetes.io/name: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: pipelines-as-code