kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipelines-as-code-webhook-role
  
  labels:
    app.kubernetes.io/version: "v0.27.1"
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: pipelines-as-code
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "update"]
    resourceNames: ["pipelines-as-code-webhook-certs"]
    # The webhook daemon makes a reconciliation loop on webhook-certs. Whenever
    # the secret changes it updates the webhook configurations with the certificates
    # stored in the secret.
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
    # webhook uses leases for leader election