# Copyright 2024 Red Hat
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This configmap is filled by bootstrap command
# GitHub App is added as provider and later this is checked
# before configuring a new GitHub App so that we don't
# configure more than one App

apiVersion: v1
data:
  # pipelines as code controller version
  version: "v0.27.1"

  # controller url to be used for configuring webhook using cli
  controller-url: ""

  # display the configured provider on the platform
  # only one provider type to be configured at a time
  # eg. if GitHub App is configured, then webhooks should not be configured
  provider: ""

kind: ConfigMap
metadata:
  name: pipelines-as-code-info
  
  labels:
    app.kubernetes.io/version: "v0.27.1"
    app.kubernetes.io/part-of: pipelines-as-code