# Webhook PDB.
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: eventing-webhook
  namespace: knative-eventing
  labels:
    app.kubernetes.io/component: eventing-webhook
    app.kubernetes.io/version: "1.14.2"
    app.kubernetes.io/name: knative-eventing
spec:
  minAvailable: 80%
  selector:
    matchLabels:
      app: eventing-webhook
