apiVersion: v1
kind: Service
metadata:
  labels:
    role: eventing-webhook
    app.kubernetes.io/component: eventing-webhook
    app.kubernetes.io/version: "1.14.2"
    app.kubernetes.io/name: knative-eventing
  name: eventing-webhook
  namespace: knative-eventing
spec:
  ports:
    - name: https-webhook
      port: 443
      targetPort: 8443
  selector:
    role: eventing-webhook
