apiVersion: networking.internal.knative.dev/v1alpha1
kind: Certificate
metadata:
  annotations:
    networking.knative.dev/certificate.class: cert-manager.certificate.networking.knative.dev
  labels:
    networking.knative.dev/certificate-type: system-internal
  name: routing-serving-certs
spec:
  dnsNames:
  - kn-routing
  - data-plane.knative.dev
  secretName: routing-serving-certs
