kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knative-serving-activator-cluster
  labels:
    serving.knative.dev/controller: "true"
    app.kubernetes.io/version: "1.14.1"
    app.kubernetes.io/name: knative-serving
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["serving.knative.dev"]
    resources: ["revisions"]
    verbs: ["get", "list", "watch"]
