apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: knative-serving-activator-cluster
  labels:
    app.kubernetes.io/component: activator
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: "1.14.1"
subjects:
  - kind: ServiceAccount
    name: activator
    namespace: knative-serving
roleRef:
  kind: ClusterRole
  name: knative-serving-activator-cluster
  apiGroup: rbac.authorization.k8s.io
