apiVersion: v1
kind: ConfigMap
metadata:
  name: config-gc
  labels:
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: 1.14.1
  annotations:
    knative.dev/example-checksum: aa3813a8
data: {}
