apiVersion: v1
kind: ConfigMap
metadata:
  name: config-autoscaler
  labels:
    app.kubernetes.io/component: autoscaler
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: 1.14.1
  annotations:
    knative.dev/example-checksum: 47c2487f
data: {}
