apiVersion: v1
kind: ConfigMap
metadata:
  name: config-observability
  labels:
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/component: observability
    app.kubernetes.io/version: 1.14.1
  annotations:
    knative.dev/example-checksum: 54abd711
data: {}
