apiVersion: v1
kind: ConfigMap
metadata:
  name: config-defaults
  labels:
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: 1.14.1
  annotations:
    knative.dev/example-checksum: 5b64ff5c
data: {}
