apiVersion: v1
kind: ConfigMap
metadata:
  name: config-deployment
  labels:
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: 1.14.1
  annotations:
    knative.dev/example-checksum: ed77183a
data:
  queue-sidecar-image: gcr.io/knative-releases/knative.dev/serving/cmd/queue@sha256:55e7d89003b3fb97ddfaf9d65326a7ccc69b437773c3eccab43cece771bc1eda
