apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: webhook-pdb
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: 1.14.1
spec:
  minAvailable: 80%
  selector:
    matchLabels:
      app: webhook
