kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knative-serving-activator
  labels:
    serving.knative.dev/controller: 'true'
    app.kubernetes.io/version: 1.14.1
    app.kubernetes.io/name: knative-serving
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  resourceNames:
  - routing-serving-certs
  - knative-serving-certs
