apiVersion: v1
kind: Service
metadata:
  labels:
    app: webhook
    role: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/version: 1.14.1
    app.kubernetes.io/name: knative-serving
  name: webhook
spec:
  ports:
  - name: http-metrics
    port: 9090
    targetPort: 9090
  - name: http-profiling
    port: 8008
    targetPort: 8008
  - name: https-webhook
    port: 443
    targetPort: 8443
  selector:
    app: webhook
    role: webhook
